sudo: required
language: java
jdk: oraclejdk11

node_js:
- '14'

services:
- mysql

before_install:
- mysql -e 'CREATE DATABASE mrsisa2021_t15';
- chmod +x mvnw
- sudo apt install nodejs

addons:
  sonarcloud:
  organization: danielbozanic
  token: $SONAR_TOKEN

script:
- "./mvnw clean install -DskipTests=false -B"
- ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=danielbozanic -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

dist: trusty

test:
  adapter: mysql2
  database: mrsisa2021_t15
  username: travis
  encoding: utf8

deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: backend 
