sudo: required
language: java
jdk: oraclejdk11

services:
  - mysql

addons:
  apt:
   sources:
    - mysql-8.0.23-trusty
   packages:
    - mysql-server
    - mysql-client

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: backend 