sudo: required
language: java
jdk: oraclejdk11

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mrsisa2021_t15';
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B

dist: trusty

test:
  adapter: mysql2
  database: mrsisa2021_t15
  username: root
  encoding: utf8

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: backend 