sudo: required
language: java
jdk: oraclejdk11

services:
  - mysql

before_install:
  - mysql -e "alter user 'root'@'localhost' identified by 'root'";
  - mysql -e "grant all on mrsisa2021_t15.* to 'root'@'%'";
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: backend 