sudo: required
language: java
jdk: oraclejdk11

services:
  - mysql

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: backend 