sudo: required
language: java
jdk: oraclejdk11

node_js:
- '14'

services:
- mysql

before_install:
- mysql -e 'CREATE DATABASE mrsisa2021_t15';
- chmod +x mvnw
- sudo apt install nodejs

addons:
  sonarcloud:
  organization: danielbozanic
  token: 
	secure: "RNQOullSun2i5WtfxGEIb9kkLoTNMyZ4xt6HBiOR4fJiOVZNJ0qT8n3AFmJUPMs65N38R6zeOK+sryPIa0OGSxXUr8WaQu7y2lcvCh9g2Bvwf7SKNv/NCuYfOSJYJMTxhpKpkcVgO0TETUVEYb2VGENc8fP2u4qMV8dmlG+p7LeACcYZ6BvKIIjitMBObi9yB7+yYtuCNvLEVEmA4JAZKlKtfTCyj0gsT2xCnwTmjhupNUf+00gK/l1jsNA3TNWQ0L7tcPN0k+Iiz91uUNBulDKNeFag9c4MDVfskVFxtPwsKsn5++b2rQ6eBbrHvSyrhQNheqQMPsJKZWzFQ4uhu++iUE2Mth1wEzkvRA0eRbtcD5vm600X+h6LNJDi9Mg1qfdcbF5a8TpBSeG9yUaVEP8In8u/FlUQZGY/VD4ckr4h8IEms4ta7SnGzrnQTw5FML8nyJn8PJHcnhyXYTlWLJxj+fdniNjpbzJjPlGjOEtJtuC62h2qoLdtYRYm6EfP1BymiQ78v7OwOkBRS515St9LV9GIj0HU+AAGsgJvoZeA9kcou9GvdplTQS/qRl2DL0QcRuh+CHE4GaOYoI1rpOkz00+orxuNSDKcd1lkFk+pywCxAI9XCX+czTwcPXmbSKar+bTIhX9T4SP/h2geLvY456MxP8tZDLIqeT7GAcE="

script:
- "./mvnw clean install -DskipTests=false -B"
-  mvn clean verify sonar:sonar -Pcoverage

dist: trusty

test:
  adapter: mysql2
  database: mrsisa2021_t15
  username: travis
  encoding: utf8

deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  app: backend 
