sudo: required
language: java
jdk: oraclejdk11

services:
  - mysql

script:
  - ./mvnw clean install -DskipTests=false -B

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: backend 